/**
 * FlashcardDecksScreen — My flashcard decks + auto-generate
 */
import React, { useState, useEffect, useCallback } from 'react';
import {
  View,
  Text,
  TouchableOpacity,
  FlatList,
  StyleSheet,
  Alert,
  ActivityIndicator,
  Modal,
  TextInput,
  RefreshControl,
} from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { LinearGradient } from 'expo-linear-gradient';
import { Ionicons } from '@expo/vector-icons';
import { useThemeStore } from '../../store/themeStore';
import { flashcardsAPI, FlashcardDeck } from '../../api/flashcards';
import { Gradients } from '../../theme';

const DECK_EMOJIS = ['📚', '📖', '🎯', '💡', '🌍', '🎓', '📝', '🔤', '🧠', '⭐'];

// Mock data for when backend is unavailable
const MOCK_DECKS: FlashcardDeck[] = [
  { id: 'mock-1', user_id: '', title: 'IELTS Environment', description: 'Key vocab for environment topics', is_public: false, card_count: 15, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: 'mock-2', user_id: '', title: 'Academic Words', description: 'Essential academic vocabulary', is_public: false, card_count: 22, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: 'mock-3', user_id: '', title: 'Pronunciation', description: 'Words I need to practice', is_public: false, card_count: 8, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
];

export default function FlashcardDecksScreen({ navigation }: any) {
  const { colors } = useThemeStore();
  const [decks, setDecks] = useState<FlashcardDeck[]>([]);
  const [loading, setLoading] = useState(true);
  const [refreshing, setRefreshing] = useState(false);
  const [showCreate, setShowCreate] = useState(false);
  const [newTitle, setNewTitle] = useState('');
  const [newDesc, setNewDesc] = useState('');
  const [creating, setCreating] = useState(false);

  const loadDecks = useCallback(async () => {
    try {
      const result = await flashcardsAPI.listDecks();
      setDecks(result.items);
    } catch {
      // Use mock data
      setDecks(MOCK_DECKS);
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => { loadDecks(); }, [loadDecks]);

  const onRefresh = useCallback(async () => {
    setRefreshing(true);
    await loadDecks();
    setRefreshing(false);
  }, [loadDecks]);

  const handleCreate = async () => {
    if (!newTitle.trim()) {
      Alert.alert('Error', 'Please enter a deck title');
      return;
    }
    setCreating(true);
    try {
      const deck = await flashcardsAPI.createDeck({
        title: newTitle.trim(),
        description: newDesc.trim() || undefined,
      });
      setDecks(prev => [deck, ...prev]);
      setShowCreate(false);
      setNewTitle('');
      setNewDesc('');
    } catch (error: any) {
      const msg = error.response?.data?.detail || 'Failed to create deck';
      Alert.alert('Error', typeof msg === 'string' ? msg : JSON.stringify(msg));
    } finally {
      setCreating(false);
    }
  };

  const handleAutoGenerate = async () => {
    Alert.alert(
      'Auto-Generate Deck',
      'Create a flashcard deck from your saved vocabulary?',
      [
        { text: 'Cancel', style: 'cancel' },
        {
          text: 'Generate',
          onPress: async () => {
            try {
              const deck = await flashcardsAPI.autoGenerateDeck({
                title: 'My Vocabulary',
                mastery_levels: ['new', 'learning'],
                max_cards: 30,
              });
              setDecks(prev => [deck, ...prev]);
              Alert.alert('Success', `Deck created with ${deck.card_count} cards!`);
            } catch {
              Alert.alert('Error', 'Failed to generate deck. Make sure you have saved vocabulary words.');
            }
          },
        },
      ]
    );
  };

  const handleDelete = (deck: FlashcardDeck) => {
    Alert.alert('Delete Deck', `Delete "${deck.title}"? This cannot be undone.`, [
      { text: 'Cancel', style: 'cancel' },
      {
        text: 'Delete',
        style: 'destructive',
        onPress: async () => {
          try {
            await flashcardsAPI.deleteDeck(deck.id);
            setDecks(prev => prev.filter(d => d.id !== deck.id));
          } catch {
            Alert.alert('Error', 'Failed to delete deck');
          }
        },
      },
    ]);
  };

  const getEmoji = (index: number) => DECK_EMOJIS[index % DECK_EMOJIS.length];

  const renderDeck = ({ item, index }: { item: FlashcardDeck; index: number }) => (
    <TouchableOpacity
      style={[styles.deckCard, { backgroundColor: colors.bgCard, borderColor: colors.border }]}
      activeOpacity={0.7}
      onPress={() => navigation.navigate('FlashcardStudy', {
        deckId: item.id,
        deckTitle: item.title,
      })}
      onLongPress={() => handleDelete(item)}
    >
      <View style={[styles.deckEmoji, { backgroundColor: colors.accentBg }]}>
        <Text style={{ fontSize: 28 }}>{getEmoji(index)}</Text>
      </View>
      <Text style={[styles.deckTitle, { color: colors.textPrimary }]} numberOfLines={2}>
        {item.title}
      </Text>
      {item.description && (
        <Text style={[styles.deckDesc, { color: colors.textMuted }]} numberOfLines={1}>
          {item.description}
        </Text>
      )}
      <View style={styles.deckFooter}>
        <View style={[styles.cardCount, { backgroundColor: colors.bgSecondary }]}>
          <Ionicons name="layers-outline" size={12} color={colors.accent} />
          <Text style={[styles.cardCountText, { color: colors.accent }]}>
            {item.card_count} cards
          </Text>
        </View>
      </View>
    </TouchableOpacity>
  );

  return (
    <SafeAreaView style={[styles.safe, { backgroundColor: colors.bgBody }]}>
      {/* Header */}
      <View style={styles.header}>
        <TouchableOpacity
          style={[styles.backBtn, { borderColor: colors.border }]}
          onPress={() => navigation.goBack()}
        >
          <Ionicons name="arrow-back" size={20} color={colors.textPrimary} />
        </TouchableOpacity>
        <Text style={[styles.title, { color: colors.textPrimary }]}>Flashcards</Text>
        <TouchableOpacity
          style={[styles.addBtn, { backgroundColor: colors.accent }]}
          onPress={() => setShowCreate(true)}
        >
          <Ionicons name="add" size={20} color="#fff" />
        </TouchableOpacity>
      </View>

      {/* Auto-Generate Banner */}
      <TouchableOpacity
        style={[styles.autoBanner, { borderColor: colors.borderAccent }]}
        onPress={handleAutoGenerate}
        activeOpacity={0.7}
      >
        <LinearGradient
          colors={Gradients.primary}
          start={{ x: 0, y: 0 }}
          end={{ x: 1, y: 1 }}
          style={styles.autoBannerGradient}
        >
          <View style={styles.autoBannerContent}>
            <View style={styles.autoBannerIcon}>
              <Text style={{ fontSize: 24 }}>✨</Text>
            </View>
            <View style={{ flex: 1 }}>
              <Text style={styles.autoBannerTitle}>Auto-Generate Deck</Text>
              <Text style={styles.autoBannerDesc}>
                Create flashcards from your saved vocabulary
              </Text>
            </View>
            <Ionicons name="chevron-forward" size={20} color="rgba(255,255,255,0.7)" />
          </View>
        </LinearGradient>
      </TouchableOpacity>

      {/* Deck Grid */}
      {loading ? (
        <View style={styles.center}>
          <ActivityIndicator size="large" color={colors.accent} />
        </View>
      ) : (
        <FlatList
          data={decks}
          renderItem={renderDeck}
          keyExtractor={(item) => item.id}
          numColumns={2}
          contentContainerStyle={styles.grid}
          columnWrapperStyle={styles.gridRow}
          showsVerticalScrollIndicator={false}
          refreshControl={
            <RefreshControl refreshing={refreshing} onRefresh={onRefresh} tintColor={colors.accent} />
          }
          ListEmptyComponent={
            <View style={styles.empty}>
              <Text style={{ fontSize: 48, marginBottom: 12 }}>🃏</Text>
              <Text style={[styles.emptyTitle, { color: colors.textPrimary }]}>
                No decks yet
              </Text>
              <Text style={[styles.emptyDesc, { color: colors.textSecondary }]}>
                Create a new deck or auto-generate from vocabulary
              </Text>
            </View>
          }
        />
      )}

      {/* Create Deck Modal */}
      <Modal visible={showCreate} animationType="slide" transparent>
        <View style={styles.modalOverlay}>
          <View style={[styles.modalCard, { backgroundColor: colors.bgCard, borderColor: colors.border }]}>
            <View style={styles.modalHeader}>
              <Text style={[styles.modalTitle, { color: colors.textPrimary }]}>New Deck</Text>
              <TouchableOpacity onPress={() => setShowCreate(false)}>
                <Ionicons name="close" size={24} color={colors.textMuted} />
              </TouchableOpacity>
            </View>

            <View style={[styles.modalInput, { backgroundColor: colors.bgInput, borderColor: colors.border }]}>
              <Ionicons name="layers-outline" size={18} color={colors.textMuted} />
              <TextInput
                style={[styles.modalInputText, { color: colors.textPrimary }]}
                placeholder="Deck title"
                placeholderTextColor={colors.textMuted}
                value={newTitle}
                onChangeText={setNewTitle}
                autoFocus
              />
            </View>

            <View style={[styles.modalInput, { backgroundColor: colors.bgInput, borderColor: colors.border }]}>
              <Ionicons name="document-text-outline" size={18} color={colors.textMuted} />
              <TextInput
                style={[styles.modalInputText, { color: colors.textPrimary }]}
                placeholder="Description (optional)"
                placeholderTextColor={colors.textMuted}
                value={newDesc}
                onChangeText={setNewDesc}
              />
            </View>

            <TouchableOpacity
              style={[styles.createBtn, { backgroundColor: colors.accent }]}
              onPress={handleCreate}
              disabled={creating}
            >
              {creating ? (
                <ActivityIndicator color="#fff" />
              ) : (
                <Text style={styles.createBtnText}>Create Deck</Text>
              )}
            </TouchableOpacity>
          </View>
        </View>
      </Modal>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  safe: { flex: 1 },
  header: {
    flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between',
    paddingHorizontal: 20, paddingTop: 8, paddingBottom: 14,
  },
  backBtn: {
    width: 38, height: 38, borderRadius: 19, borderWidth: 1,
    alignItems: 'center', justifyContent: 'center',
  },
  title: { fontFamily: 'PlusJakartaSans-Bold', fontSize: 22 },
  addBtn: {
    width: 38, height: 38, borderRadius: 19,
    alignItems: 'center', justifyContent: 'center',
  },
  autoBanner: { marginHorizontal: 20, borderRadius: 16, overflow: 'hidden', marginBottom: 16, borderWidth: 0 },
  autoBannerGradient: { borderRadius: 16, padding: 18 },
  autoBannerContent: { flexDirection: 'row', alignItems: 'center', gap: 14 },
  autoBannerIcon: {
    width: 48, height: 48, borderRadius: 24,
    backgroundColor: 'rgba(255,255,255,0.2)',
    alignItems: 'center', justifyContent: 'center',
  },
  autoBannerTitle: {
    fontFamily: 'PlusJakartaSans-Bold', fontSize: 16, color: '#fff', marginBottom: 3,
  },
  autoBannerDesc: {
    fontFamily: 'PlusJakartaSans-Regular', fontSize: 12, color: 'rgba(255,255,255,0.8)',
  },
  center: { flex: 1, justifyContent: 'center', alignItems: 'center' },
  grid: { paddingHorizontal: 20, paddingBottom: 100, gap: 12 },
  gridRow: { gap: 12 },
  deckCard: {
    flex: 1, padding: 16, borderRadius: 16, borderWidth: 1,
    shadowColor: '#000', shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.04, shadowRadius: 3, elevation: 1,
  },
  deckEmoji: {
    width: 56, height: 56, borderRadius: 16,
    alignItems: 'center', justifyContent: 'center', marginBottom: 12,
  },
  deckTitle: { fontFamily: 'PlusJakartaSans-Bold', fontSize: 15, marginBottom: 4 },
  deckDesc: { fontFamily: 'PlusJakartaSans-Regular', fontSize: 12, marginBottom: 10 },
  deckFooter: { marginTop: 'auto' },
  cardCount: {
    flexDirection: 'row', alignItems: 'center', gap: 4,
    paddingHorizontal: 10, paddingVertical: 4, borderRadius: 999, alignSelf: 'flex-start',
  },
  cardCountText: { fontFamily: 'PlusJakartaSans-SemiBold', fontSize: 11 },
  empty: { alignItems: 'center', paddingTop: 80 },
  emptyTitle: { fontFamily: 'PlusJakartaSans-Bold', fontSize: 20, marginBottom: 8 },
  emptyDesc: { fontFamily: 'PlusJakartaSans-Regular', fontSize: 14, textAlign: 'center', lineHeight: 20 },
  // Modal
  modalOverlay: {
    flex: 1, justifyContent: 'flex-end',
    backgroundColor: 'rgba(0,0,0,0.5)',
  },
  modalCard: {
    borderTopLeftRadius: 24, borderTopRightRadius: 24,
    borderWidth: 1, padding: 24, paddingBottom: 40,
  },
  modalHeader: {
    flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center',
    marginBottom: 24,
  },
  modalTitle: { fontFamily: 'PlusJakartaSans-Bold', fontSize: 20 },
  modalInput: {
    flexDirection: 'row', alignItems: 'center', gap: 12,
    borderRadius: 14, borderWidth: 1, paddingHorizontal: 16,
    marginBottom: 14,
  },
  modalInputText: {
    flex: 1, fontFamily: 'PlusJakartaSans-Regular', fontSize: 15,
    paddingVertical: 14,
  },
  createBtn: {
    height: 52, borderRadius: 26, alignItems: 'center', justifyContent: 'center',
    marginTop: 8,
  },
  createBtnText: { fontFamily: 'PlusJakartaSans-Bold', fontSize: 16, color: '#fff' },
});
