/**
 * Flashcard API service
 */
import apiClient from './client';

export interface FlashcardDeck {
  id: string;
  user_id: string;
  title: string;
  description: string | null;
  is_public: boolean;
  card_count: number;
  created_at: string;
  updated_at: string;
}

export interface FlashcardCard {
  id: string;
  deck_id: string;
  vocabulary_id: string | null;
  front_content: string;
  back_content: string;
  audio_url: string | null;
  extra_info: any;
  order_index: number;
}

export interface ReviewResult {
  flashcard_id: string;
  next_review_at: string;
  interval_days: number;
  easiness_factor: number;
  repetition_number: number;
}

export const flashcardsAPI = {
  listDecks: async (): Promise<{ items: FlashcardDeck[]; total: number }> => {
    const { data } = await apiClient.get('/flashcards/decks');
    return data;
  },

  createDeck: async (payload: { title: string; description?: string; is_public?: boolean }): Promise<FlashcardDeck> => {
    const { data } = await apiClient.post('/flashcards/decks', payload);
    return data;
  },

  getDeckDetail: async (deckId: string): Promise<{ deck: FlashcardDeck; cards: FlashcardCard[] }> => {
    const { data } = await apiClient.get(`/flashcards/decks/${deckId}`);
    return data;
  },

  updateDeck: async (deckId: string, payload: { title?: string; description?: string }) => {
    const { data } = await apiClient.patch(`/flashcards/decks/${deckId}`, payload);
    return data;
  },

  deleteDeck: async (deckId: string) => {
    await apiClient.delete(`/flashcards/decks/${deckId}`);
  },

  addCard: async (deckId: string, payload: {
    front_content: string;
    back_content: string;
    audio_url?: string;
    vocabulary_id?: string;
    extra_info?: any;
  }): Promise<FlashcardCard> => {
    const { data } = await apiClient.post(`/flashcards/decks/${deckId}/cards`, payload);
    return data;
  },

  deleteCard: async (cardId: string) => {
    await apiClient.delete(`/flashcards/cards/${cardId}`);
  },

  reviewCard: async (cardId: string, qualityRating: number): Promise<ReviewResult> => {
    const { data } = await apiClient.post(`/flashcards/cards/${cardId}/review`, {
      quality_rating: qualityRating,
    });
    return data;
  },

  getStudySession: async (deckId: string): Promise<{
    deck: FlashcardDeck;
    cards_to_study: FlashcardCard[];
    total_due: number;
  }> => {
    const { data } = await apiClient.get(`/flashcards/decks/${deckId}/study`);
    return data;
  },

  autoGenerateDeck: async (payload: {
    title: string;
    mastery_levels: string[];
    max_cards?: number;
  }): Promise<FlashcardDeck> => {
    const { data } = await apiClient.post('/flashcards/decks/auto-generate', payload);
    return data;
  },
};
