"""
Pydantic schemas for Flashcards
"""
import uuid
from datetime import datetime
from pydantic import BaseModel, Field


class CreateDeckRequest(BaseModel):
    title: str = Field(..., min_length=1, max_length=255)
    description: str | None = None
    is_public: bool = False


class UpdateDeckRequest(BaseModel):
    title: str | None = Field(None, min_length=1, max_length=255)
    description: str | None = None
    is_public: bool | None = None


class DeckResponse(BaseModel):
    id: uuid.UUID
    title: str
    description: str | None
    is_public: bool
    card_count: int
    created_at: datetime
    updated_at: datetime

    model_config = {"from_attributes": True}


class DeckListResponse(BaseModel):
    items: list[DeckResponse]
    total: int


class AddCardRequest(BaseModel):
    front_content: str = Field(..., min_length=1)
    back_content: str = Field(..., min_length=1)
    audio_url: str | None = None
    vocabulary_id: uuid.UUID | None = None
    extra_info: dict | None = None


class CardResponse(BaseModel):
    id: uuid.UUID
    front_content: str
    back_content: str
    audio_url: str | None
    extra_info: dict | None
    order_index: int

    model_config = {"from_attributes": True}


class DeckDetailResponse(BaseModel):
    deck: DeckResponse
    cards: list[CardResponse]


class ReviewCardRequest(BaseModel):
    quality_rating: int = Field(..., ge=0, le=5)
    # 0=blackout, 1=incorrect, 2=incorrect but remembered, 3=hard, 4=correct, 5=easy


class ReviewCardResponse(BaseModel):
    flashcard_id: uuid.UUID
    next_review_at: datetime
    interval_days: int
    easiness_factor: float
    repetition_number: int


class StudySessionResponse(BaseModel):
    deck: DeckResponse
    cards_to_study: list[CardResponse]
    total_due: int


class AutoGenerateDeckRequest(BaseModel):
    title: str = Field(..., min_length=1, max_length=255)
    mastery_levels: list[str] = ["new", "learning"]
    max_cards: int = Field(default=50, ge=1, le=200)
