"""
Flashcard API routes
"""
from uuid import UUID
from datetime import datetime, timedelta, timezone
from fastapi import APIRouter, Depends, HTTPException, status
from sqlalchemy import select, func
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.orm import selectinload

from app.database import get_db
from app.api.deps import get_current_user
from app.models.user import User
from app.models.flashcard import FlashcardDeck, Flashcard, FlashcardReview
from app.models.vocabulary import VocabularyNote
from app.schemas.flashcard import (
    CreateDeckRequest, UpdateDeckRequest,
    DeckResponse, DeckListResponse, DeckDetailResponse,
    AddCardRequest, CardResponse,
    ReviewCardRequest, ReviewCardResponse,
    StudySessionResponse,
    AutoGenerateDeckRequest,
)

router = APIRouter(prefix="/flashcards", tags=["Flashcards"])


@router.get("/decks", response_model=DeckListResponse)
async def list_decks(
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """List all flashcard decks for the current user."""
    result = await db.execute(
        select(FlashcardDeck)
        .where(FlashcardDeck.user_id == current_user.id)
        .order_by(FlashcardDeck.updated_at.desc())
    )
    decks = result.scalars().all()
    return DeckListResponse(
        items=[DeckResponse.model_validate(d) for d in decks],
        total=len(decks),
    )


@router.post("/decks", response_model=DeckResponse, status_code=status.HTTP_201_CREATED)
async def create_deck(
    request: CreateDeckRequest,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """Create a new flashcard deck."""
    deck = FlashcardDeck(
        user_id=current_user.id,
        title=request.title,
        description=request.description,
        is_public=request.is_public,
    )
    db.add(deck)
    await db.flush()
    return DeckResponse.model_validate(deck)


@router.get("/decks/{deck_id}", response_model=DeckDetailResponse)
async def get_deck_detail(
    deck_id: UUID,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """Get deck detail with all cards."""
    result = await db.execute(
        select(FlashcardDeck)
        .options(selectinload(FlashcardDeck.cards))
        .where(
            FlashcardDeck.id == deck_id,
            FlashcardDeck.user_id == current_user.id,
        )
    )
    deck = result.scalar_one_or_none()
    if not deck:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Deck not found")

    return DeckDetailResponse(
        deck=DeckResponse.model_validate(deck),
        cards=[CardResponse.model_validate(c) for c in deck.cards],
    )


@router.patch("/decks/{deck_id}", response_model=DeckResponse)
async def update_deck(
    deck_id: UUID,
    request: UpdateDeckRequest,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """Update a flashcard deck."""
    result = await db.execute(
        select(FlashcardDeck).where(
            FlashcardDeck.id == deck_id,
            FlashcardDeck.user_id == current_user.id,
        )
    )
    deck = result.scalar_one_or_none()
    if not deck:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Deck not found")

    for field, value in request.model_dump(exclude_unset=True).items():
        setattr(deck, field, value)
    await db.flush()
    return DeckResponse.model_validate(deck)


@router.delete("/decks/{deck_id}", status_code=status.HTTP_204_NO_CONTENT)
async def delete_deck(
    deck_id: UUID,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """Delete a flashcard deck."""
    result = await db.execute(
        select(FlashcardDeck).where(
            FlashcardDeck.id == deck_id,
            FlashcardDeck.user_id == current_user.id,
        )
    )
    deck = result.scalar_one_or_none()
    if not deck:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Deck not found")
    await db.delete(deck)


@router.post("/decks/{deck_id}/cards", response_model=CardResponse, status_code=status.HTTP_201_CREATED)
async def add_card(
    deck_id: UUID,
    request: AddCardRequest,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """Add a card to a deck."""
    # Verify deck ownership
    result = await db.execute(
        select(FlashcardDeck).where(
            FlashcardDeck.id == deck_id,
            FlashcardDeck.user_id == current_user.id,
        )
    )
    deck = result.scalar_one_or_none()
    if not deck:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Deck not found")

    card = Flashcard(
        deck_id=deck_id,
        front_content=request.front_content,
        back_content=request.back_content,
        audio_url=request.audio_url,
        vocabulary_id=request.vocabulary_id,
        extra_info=request.extra_info,
        order_index=deck.card_count,
    )
    db.add(card)
    deck.card_count += 1
    await db.flush()
    return CardResponse.model_validate(card)


@router.delete("/cards/{card_id}", status_code=status.HTTP_204_NO_CONTENT)
async def delete_card(
    card_id: UUID,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """Delete a flashcard."""
    result = await db.execute(
        select(Flashcard)
        .join(FlashcardDeck)
        .where(Flashcard.id == card_id, FlashcardDeck.user_id == current_user.id)
    )
    card = result.scalar_one_or_none()
    if not card:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Card not found")

    # Decrement deck card count
    deck_result = await db.execute(select(FlashcardDeck).where(FlashcardDeck.id == card.deck_id))
    deck = deck_result.scalar_one()
    deck.card_count = max(0, deck.card_count - 1)

    await db.delete(card)


@router.post("/cards/{card_id}/review", response_model=ReviewCardResponse)
async def review_card(
    card_id: UUID,
    request: ReviewCardRequest,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """Record a flashcard review result using SM-2 algorithm."""
    # Verify card exists and belongs to user
    result = await db.execute(
        select(Flashcard)
        .join(FlashcardDeck)
        .where(Flashcard.id == card_id, FlashcardDeck.user_id == current_user.id)
    )
    card = result.scalar_one_or_none()
    if not card:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Card not found")

    # Get the latest review for this card by this user
    last_review_result = await db.execute(
        select(FlashcardReview)
        .where(
            FlashcardReview.flashcard_id == card_id,
            FlashcardReview.user_id == current_user.id,
        )
        .order_by(FlashcardReview.reviewed_at.desc())
        .limit(1)
    )
    last_review = last_review_result.scalar_one_or_none()

    # SM-2 Algorithm
    q = request.quality_rating
    if last_review:
        ef = last_review.easiness_factor
        rep = last_review.repetition_number
        interval = last_review.interval_days
    else:
        ef = 2.5
        rep = 0
        interval = 1

    # Update easiness factor
    new_ef = ef + (0.1 - (5 - q) * (0.08 + (5 - q) * 0.02))
    new_ef = max(1.3, new_ef)

    if q < 3:
        # Reset
        new_rep = 0
        new_interval = 1
    else:
        new_rep = rep + 1
        if new_rep == 1:
            new_interval = 1
        elif new_rep == 2:
            new_interval = 6
        else:
            new_interval = round(interval * new_ef)

    next_review = datetime.now(timezone.utc) + timedelta(days=new_interval)

    review = FlashcardReview(
        flashcard_id=card_id,
        user_id=current_user.id,
        quality_rating=q,
        easiness_factor=round(new_ef, 2),
        interval_days=new_interval,
        repetition_number=new_rep,
        next_review_at=next_review,
    )
    db.add(review)
    await db.flush()

    return ReviewCardResponse(
        flashcard_id=card_id,
        next_review_at=next_review,
        interval_days=new_interval,
        easiness_factor=round(new_ef, 2),
        repetition_number=new_rep,
    )


@router.get("/decks/{deck_id}/study", response_model=StudySessionResponse)
async def get_study_session(
    deck_id: UUID,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """Get cards due for study in this deck (SRS-ordered)."""
    result = await db.execute(
        select(FlashcardDeck)
        .where(FlashcardDeck.id == deck_id, FlashcardDeck.user_id == current_user.id)
    )
    deck = result.scalar_one_or_none()
    if not deck:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Deck not found")

    now = datetime.now(timezone.utc)

    # Get cards that are due or never reviewed
    # Using a subquery to get the latest review for each card
    cards_result = await db.execute(
        select(Flashcard)
        .where(Flashcard.deck_id == deck_id)
        .order_by(Flashcard.order_index)
    )
    all_cards = cards_result.scalars().all()

    due_cards = []
    for card in all_cards:
        latest_review = await db.execute(
            select(FlashcardReview)
            .where(
                FlashcardReview.flashcard_id == card.id,
                FlashcardReview.user_id == current_user.id,
            )
            .order_by(FlashcardReview.reviewed_at.desc())
            .limit(1)
        )
        review = latest_review.scalar_one_or_none()

        if not review or (review.next_review_at and review.next_review_at <= now):
            due_cards.append(card)

    return StudySessionResponse(
        deck=DeckResponse.model_validate(deck),
        cards_to_study=[CardResponse.model_validate(c) for c in due_cards[:20]],
        total_due=len(due_cards),
    )


@router.post("/decks/auto-generate", response_model=DeckResponse, status_code=status.HTTP_201_CREATED)
async def auto_generate_deck(
    request: AutoGenerateDeckRequest,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """Auto-generate a flashcard deck from user's saved vocabulary."""
    # Get vocabulary notes matching criteria
    result = await db.execute(
        select(VocabularyNote)
        .where(
            VocabularyNote.user_id == current_user.id,
            VocabularyNote.mastery_level.in_(request.mastery_levels),
        )
        .order_by(VocabularyNote.created_at.desc())
        .limit(request.max_cards)
    )
    vocab_notes = result.scalars().all()

    if not vocab_notes:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="No vocabulary notes found matching the criteria"
        )

    # Create deck
    deck = FlashcardDeck(
        user_id=current_user.id,
        title=request.title,
        description=f"Auto-generated from {len(vocab_notes)} vocabulary notes",
        card_count=len(vocab_notes),
    )
    db.add(deck)
    await db.flush()

    # Create cards from vocabulary
    for i, note in enumerate(vocab_notes):
        definitions_text = ""
        if note.definitions:
            for d in note.definitions[:2]:
                pos = d.get("part_of_speech", "")
                defn = d.get("definition", "")
                definitions_text += f"({pos}) {defn}\n"

        card = Flashcard(
            deck_id=deck.id,
            vocabulary_id=note.id,
            front_content=note.word,
            back_content=definitions_text.strip() or "No definition available",
            audio_url=note.audio_url,
            extra_info={"phonetic": note.phonetic},
            order_index=i,
        )
        db.add(card)

    await db.flush()
    return DeckResponse.model_validate(deck)
